services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: calendar-conflict-optimizer
    container_name: calendar-conflict-optimizer
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-docker}
      - DB_URL=jdbc:postgresql://db:5432/calendar-conflict-optimizer
      - DB_USERNAME=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-calendar-realm}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-calendar-client}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      keycloak:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - calender-optimizer-network

  db:
    image: postgres:17-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    container_name: postgres-db
    environment:
      - POSTGRES_DB=calendar-conflict-optimizer
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - calender-optimizer-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    networks:
      - calender-optimizer-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/calendar-conflict-optimizer
      - KC_DB_USERNAME=${DB_USER:-postgres}
      - KC_DB_PASSWORD=${DB_PASSWORD:-postgres}
      - KC_HOSTNAME=localhost
      - KC_PROXY=edge
    ports:
      - "8081:8080"
    depends_on:
      - db
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import
    networks:
      - calender-optimizer-network
    command: ["start-dev", "--import-realm"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - calender-optimizer-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
    depends_on:
      - elasticsearch
    networks:
      - calender-optimizer-network

volumes:
  postgres-data:
  redis-data:
  elasticsearch-data:

networks:
  calender-optimizer-network:
    driver: bridge