spring:
  application:
    name: calendar-conflict-optimizer
server:
  port: 8089

  datasource:
    url: jdbc:postgresql://localhost:5432/calendar-conflict-optimizer
    validationQuery: SELECT 1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    poolsize:
      min: 1
      max: 5

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update