spring:
  application:
    name: calendar-conflict-optimizer
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/calendar-conflict-optimizer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
      initialization-fail-timeout: 1

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  # JPA/Hibernate Configuration - Change the DDL to 'update' to be work with Flyway
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

  data:
    elasticsearch:
      uris: http://localhost:9200
      repositories:
        enabled: true



  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/property-rental

server:
  port: 8089
