-- flyway formatted sql
-- Changeset Ahmed:1

-- First create the users table (since properties and bookings depend on it)
create table users (
                       id   bigint generated by default as identity primary key,
                       name varchar(255) not null
);

-- Next, create the properties table (depends on users)
create table properties (
                            id        bigint generated by default as identity primary key,
                            amenities varchar(255) not null,
                            location  varchar(255) not null,
                            title     varchar(255) not null,
                            owner_id  bigint not null
                                constraint fk_properties_owner
                                    references users
);

-- Finally, create the bookings table (depends on users and properties)
create table bookings (
                          id          bigint generated by default as identity primary key,
                          start_date  date not null,
                          end_date    date not null,
                          property_id bigint not null
                              constraint fk_bookings_property
                                  references properties,
                          user_id     bigint not null
                              constraint fk_bookings_user
                                  references users
);
